name: Aero
options:
  bundleIdPrefix: com.aero
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: ""
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.2"
    CURRENT_PROJECT_VERSION: "3"
targets:
  Aero:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Aero
        excludes:
          - "Info.plist"
          - "Resources/Wallpapers"
          - "Resources/Fonts"
          - "Resources/Help"
          - "Resources/Blocklists"
      - path: Aero/Resources/Wallpapers
        type: folder
      - path: Aero/Resources/Fonts
        type: folder
      - path: Aero/Resources/Help
        type: folder
      - path: Aero/Resources/Blocklists
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aero.browser
        INFOPLIST_FILE: Aero/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        PRODUCT_NAME: Aero
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
